# Generated by Django 4.2 on 2025-06-29 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_add_card_id_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardinfo',
            name='savingID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bank_app.deposit', verbose_name='存款类型'),
        ),
        migrations.AlterModelTable(
            name='bankuser',
            table='bank_app_bankuser',
        ),
    ]
